### PR TITLE
remove leftover dependency six

### PR DESCRIPTION
**Pull request by a-detiste**
This was catched recently

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1073437

### CODE REVIEW

**Comment by davidt** [comment]
Thanks for this. I'm going to land a slightly modified version.

Does Debian need us to cut a release?

**Comment by a-detiste** [comment]
A release would be nice.

Le jeu. 11 juil. 2024, 17:16, David Trowbridge ***@***.***> a
écrit :

**Comment by davidt** [comment]
We'll get that done soon. Thanks again for the contribution!

**Comment by a-detiste** [comment]
thanks

**Pull request closed without merging**
